### ISSUE TITLE
install glove-python on linux 

### ISSUE THREAD

**Issue by ty2009137128** [maciejkula/glove-python#103]
hi，if you install glove-python on linux you can try some steps as:
1. install gcc  , "yum install gcc"
2. install cython ， pip , python or conda install cython and make sure cython.version>0.29
3. cython **. pyx ，just looke this https://github.com/maciejkula/glove-python/issues/96#issuecomment-483561454
4. over write setup.py and https://github.com/maciejkula/glove-python/issues/42#issuecomment-325650191
5. the last python setup.py install ,it would be ok.

**Comment by obaidullahzaland** [comment]
Hi, 
after doing all the above procedures as said. I am getting the following error
>>> from glove import Glove
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zaland/glove-python/glove/__init__.py", line 1, in <module>
    from .corpus import Corpus
  File "/home/zaland/glove-python/glove/corpus.py", line 10, in <module>
    from .corpus_cython import construct_cooccurrence_matrix
ModuleNotFoundError: No module named 'glove.corpus_cython'
>>> exit()

**Comment by IronFarm** [comment]
@obaidullahzaland if you installed Glove by deleting the `stdc++` dependency then Glove will **not work**. The dependency is there because it is needed.

**Comment by padriba** [comment]
Hi
if you get this error 
`glove/corpus_cython.cpp: In function ‘void __pyx_f_5glove_13corpus_cython_increment_matrix(__pyx_t_5glove_13corpus_cython_SparseRowMatrix*, int, int, float)’:
glove/corpus_cython.cpp:2619:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_1 = ((__pyx_v_row >= __pyx_v_mat->indices->size()) != 0);
                   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
glove/corpus_cython.cpp:2761:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   __pyx_t_1 = ((__pyx_v_idx == __pyx_v_row_indices->size()) != 0);
                 ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
glove/corpus_cython.cpp: In function ‘int __pyx_f_5glove_13corpus_cython_matrix_nnz(__pyx_t_5glove_13corpus_cython_SparseRowMatrix*)’:
glove/corpus_cython.cpp:2952:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (__pyx_t_3 = 0; __pyx_t_3 < __pyx_t_2; __pyx_t_3+=1) {
                       ~~~~~~~~~~^~~~~~~~~~~
glove/corpus_cython.cpp: In function ‘PyObject* __pyx_f_5glove_13corpus_cython_matrix_to_coo(__pyx_t_5glove_13corpus_cython_SparseRowMatrix*, int)’:
glove/corpus_cython.cpp:3222:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_13 = 0; __pyx_t_13 < __pyx_t_12; __pyx_t_13+=1) {`

you just need to add `unsigned`  as suggest by this [link](https://stackoverflow.com/a/3660928/12861290) to the lines mentioned by warnings example : 
`__pyx_t_1 = (((unsigned) __pyx_v_row >= __pyx_v_mat->indices->size()) != 0);`
