### ISSUE TITLE
Failed installing  on win10 use “pip install glove-python-binary”

### ISSUE THREAD

**Issue by hesterLong** [maciejkula/glove-python#113]
after I use command "pip install glove-python-binary" to install,
I got a wrong feedback when i import it.
` 
(glove) D:\python_project\education_data\transformer_model\glove-python>python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from glove import Glove
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python_project\education_data\transformer_model\glove-python\glove\__init__.py", line 1, in <module>
    from .corpus import Corpus
  File "D:\python_project\education_data\transformer_model\glove-python\glove\corpus.py", line 10, in <module>
    from .corpus_cython import construct_cooccurrence_matrix
ModuleNotFoundError: No module named 'glove.corpus_cython'
>>> 
`
how can I fix it ?

**Comment by IronFarm** [comment]
@hesterLong it looks to me like it's importing glove from your local directory instead of where the package is installed. Could you try and import it after starting python in another directory? i.e. run python in `D:\` for example then `from glove import Glove`
