### ISSUE TITLE
installation failed on Windows 10

### ISSUE THREAD

**Issue by ZenMoore** [maciejkula/glove-python#118]
I have followed the installation guidance in Wiki, but still failed.
Environment : `Windows 10` `Python 3.7` `MinGW 8.2.0-4`
Here is the log :
```cmd
(venv) D:\Python\glove-python>python setup.py build_ext --compiler=mingw32
D:\venv\lib\site-packages\setuptools\dist.py:700: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore
name 'description_file' instead
  % (opt, underscore_opt))
running build_ext
Traceback (most recent call last):
  File "setup.py", line 155, in <module>
    ext_modules=define_extensions()
  File "D:\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Python\Python 3.7.4\Lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Python\Python 3.7.4\Lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\Python\Python 3.7.4\Lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\venv\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\venv\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Python\Python 3.7.4\Lib\distutils\command\build_ext.py", line 309, in run
    force=self.force)
  File "D:\Python\Python 3.7.4\Lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\Python\Python 3.7.4\Lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "D:\Python\Python 3.7.4\Lib\distutils\cygwinccompiler.py", line 157, in __init__
    self.dll_libraries = get_msvcr()
  File "D:\Python\Python 3.7.4\Lib\distutils\cygwinccompiler.py", line 86, in get_msvcr
    raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1916
```
Key Error : `ValueError: Unknown MS Compiler version 1916`

**Comment by Tsadoq** [comment]
I have the very same problem

**Comment by kerneltravel** [comment]
may caused by 32bit / 64bit python and lib mis-match
