### ISSUE TITLE
unable to install it on OSX 

### ISSUE THREAD

**Issue by anujgupta82** [maciejkula/glove-python#31]
I am consistently getting the following error:

gcc-4.9: error: unrecognized command line option '-Wshorten-64-to-32'

**Comment by maciejkula** [comment]
This is similar to https://github.com/lyst/lightfm/issues/29, please try using a Python distribution from Homebrew.

**Comment by maciejkula** [comment]
Any luck?

**Comment by tttthomasssss** [comment]
hey @maciejkula, i have the same problem (on OS X 10.9.5), i setup a new `virtualenv` explicitely specifying the python (3.5) binary from `homebrew`, my `gcc` version (5.3.0) should be up-to-date (at least according to `brew`; it also should be properly linked), however `setup.py` still seems to be executed with `clang`, error being:

```
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

**Comment by maciejkula** [comment]
I don't have access to a mac, so I can't really help. Maybe for some reason you are still using the clang linker? This may be related: http://stackoverflow.com/questions/9369827/how-do-i-specify-the-linker-when-building-python-extensions

I would really appreciate your help on this!

**Comment by tttthomasssss** [comment]
still looking into it, explicitly setting the `CC` flag with `env CC="path/to/gcc" pip install glove_python --no-cache-dir` does use the specified `gcc` compiler but fails with a ton of `no such instruction` errors:

```
...
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45847:no such instruction: `vmovsd -3048(%rbp), %xmm4'
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45856:no such instruction: `vmovsd %xmm4, -2984(%rbp)'
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45860:no such instruction: `vmovsd -2984(%rbp), %xmm4'
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45881:no such instruction: `vmovsd %xmm4, -3048(%rbp)'
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45885:no such instruction: `vmovsd -3048(%rbp), %xmm4'
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45894:no such instruction: `vmovsd %xmm4, -3048(%rbp)'
    /var/folders/03/fg80c1gs1_d9sws8l78p_1j8001bhn/T//ccRsFssG.s:45898:no such instruction: `vmovsd -3048(%rbp), %xmm4'
...
```

**Comment by maciejkula** [comment]
My guess here is that it's using the wrong assembler/incorrect architecture flags.

One option to side-step all these issues would be for me to have a separate non-multithreaded code path for OSX. Would that be an attractive option for you?

**Comment by tttthomasssss** [comment]
it will certainly do for now, thank you very much!!

i'll try to look a bit further into the issue myself when i get the time and will report any findings here if thats ok with you.

**Comment by maciejkula** [comment]
Yes that's great. It might take me a while to get a non-openmp version
though

**Comment by tttthomasssss** [comment]
ok i got it working, the options you have to set are quite amusing i find...

1) i had to explicitly set the `CC` flag: `export CC="/usr/local/bin/gcc-5"`
2) i had to set some additional compiler flags: `export CFLAGS="-Wa,-q"`

`-Wa` passes whatever comes after the comma to the assembler, and the `-q` option switches from the GNU assembler to the clang assembler...so don't compile with clang but use its assembler!

after that, `pip install glove_python` worked fine. As you already said in the docs, the python interpreter needs to be from `brew` and _not_ the system inbuilt one.

I can update the `setup.py` and send you a PR, but it may take a couple of days.

**Comment by maciejkula** [comment]
I have seen this before. The problem with this approach is that this breaks other stuff as far as I can remember, like installing with Anaconda.

**Comment by maciejkula** [comment]
The ideal solution would be to have a build process that test this on several OSX configurations. I'll have to look into that.

**Comment by tttthomasssss** [comment]
ok, i just had a colleague testing it with `anaconda`. he had to manually replace `clang` with `gcc` (from `brew`) as well, but he didn't have to do the `CFLAGS` business to fix the assembler.

i'll see if i can modify `setup.py` to get it to seamlessly install on os x with either `virtualenv` or `conda`.

**Comment by tcoyze** [comment]
Were you able to fix your issue @tttthomasssss ?

**Comment by tttthomasssss** [comment]
@tcoyze yes, if you're using `virtualenv`, then the steps I described in [this](https://github.com/maciejkula/glove-python/issues/31#issuecomment-175504448) comment above should work.

If you're using `anaconda` then you don't have to set any `CFLAGS` prior to installation.

Definitely make sure you're using a python version installed from e.g. `brew`. It doesn't work with the OS X inbuilt one.

**Comment by tcoyze** [comment]
@tttthomasssss Installation worked with your settings, however, I am unable to access the modules with ```from glove import Glove, Corpus```
as it raises a cryptic (at least for me) issue:

> Traceback (most recent call last):
File "build_glove.py", line 15, in 
from glove import Glove
File "/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/init.py", line 1, in 
from .corpus import Corpus
File "/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/corpus.py", line 10, in
from .corpus_cython import construct_cooccurrence_matrix
ImportError: dlopen(/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/corpus_cython.so, 2): no suitable image found. Did find:
/Users/tyler/gitlab/parsing/quero/venv/lib/python2.7/site-packages/glove/corpus_cython.so: mach-o, but wrong architecture

I created a new issue, but seeing as no one has responded to it I thought you may know of a solution?

**Comment by tttthomasssss** [comment]
Haven't seen this before but it looks like something (cython?) is compiled for the wrong architecture. Is cython installed correctly on your machine?

**Comment by tcoyze** [comment]
I'm assuming it is, I used the typical ```pip install cython```
when typing ```$ arch``` the output is ```i386```

**Comment by SriniNaga** [comment]
$env CC=/usr/local/Cellar/gcc/6.3.0_1/bin/gcc-6 pip install glove_python
This worked for me

**Comment by ok-ok-ok-ok** [comment]
workaround for MacOS Sierra 10.12.4:

$ brew install clang-omp
$ sudo -s
\# export CC="/usr/local/Cellar/clang-omp/2015-04-01/libexec/bin/clang"
\# pip install glove_python
